apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
  namespace: argocd
spec:
  destination:
    namespace: bgdk
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/richinex/bgd-kustomize.git
    path: kustomize-installation
    targetRevision: main
  syncPolicy:
    automated: {}