---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgdk
spec:
  type: LoadBalancer
  ports:
  - port: 80         # Port that external traffic will come in on
    targetPort: 8080 # Port your application is listening on inside the pod. Adjust if your app listens on a different port.
    protocol: TCP
  selector:
    app: bgd
